version: "3.9"

services:
  django:
    container_name: drf-tutor
    restart: always
    links:
      - db:db
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - env.example
  db:
    container_name: backend-postgres
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root